env:
  browser: true
  es2020: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
settings:
  import/extensions: ["js", "jsx", "ts", "tsx"]
  import/resolver:
    typescript: {}
