env:
  browser: true
  es2020: true
  jest: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  import/prefer-default-export: 0
  class-methods-use-this: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars": error
settings:
  import/extensions: ["js", "jsx", "ts", "tsx"]
  import/resolver:
    typescript: {}
