swagger: "2.0"
info:
  description: This is the official documentation for the tasks manager API.
  version: 0.1.0
  title: Tasks Manager API
basePath: /v1
host: localhost
tags:
  - name: task
    description: Operations about tasks
schemes:
  - https
  - http
paths:
  /tasks:
    get:
      tags:
        - task
      summary: Show a list of all tasks
      description: Return a paginated array with tasks
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: page
          type: integer
          minimum: 1
          description: Page of the results
        - in: query
          name: limit
          type: integer
          minimum: 1
          maximum: 100
          description: Number of results to show per page
        - in: query
          name: title
          type: string
          description: Filter results by the title
        - in: query
          name: description
          type: string
          description: Filter results by the description
        - in: query
          name: status
          type: string
          enum: ["pending", "in progress", "done"]
          description: Filter results by status
        - in: query
          name: orderById
          type: string
          enum: ["ASC", "DESC"]
          description: Order results by id
      responses:
        200:
          description: Return an object with an array of tasks and the total results
          schema:
            type: object
            properties:
              tasks:
                type: array
                items:
                  $ref: "#/definitions/Task"
              total:
                type: integer
                description: Total of records in database (using the current filters)
              totalPages:
                type: integer
                description: Total number of pages
        422:
          description: Missing required parameters or invalid properties type
        503:
          description: Service or database unavailable
    post:
      tags:
        - task
      summary: Create a new task
      description: Return the new created task
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: payload
          description: Data of the task that will be created
          required: true
          schema:
            $ref: "#/definitions/CreateTaskDto"
      responses:
        200:
          description: Return the new created the task
          schema:
            $ref: "#/definitions/Task"
        422:
          description: Missing required parameters or invalid properties type
        503:
          description: Service or database unavailable
  /tasks/{id}:
    get:
      tags:
        - task
      summary: Get a single task
      description: Return a single task by id
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: number
          required: true
          description: The id of the task
      responses:
        200:
          description: Return the task
          schema:
            $ref: "#/definitions/Task"
        422:
          description: Missing required parameters or invalid properties type
        503:
          description: Service or database unavailable
    put:
      tags:
        - task
      summary: Update a task
      description: Update a task by id
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: number
          required: true
          description: The id of the task
        - in: body
          name: payload
          description: Data of the task that will be updated
          required: true
          schema:
            $ref: "#/definitions/UpdateTaskDto"
      responses:
        200:
          description: Return the updated task
          schema:
            $ref: "#/definitions/Task"
        422:
          description: Missing required parameters or invalid properties type
        503:
          description: Service or database unavailable
    patch:
      tags:
        - task
      summary: Update a task partially
      description: Update a task partially by id
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: number
          required: true
          description: The id of the task
        - in: body
          name: payload
          description: Data of the task that will be updated
          required: true
          schema:
            $ref: "#/definitions/UpdateTaskPartiallyDto"
      responses:
        200:
          description: Return the updated task
          schema:
            $ref: "#/definitions/Task"
        422:
          description: Missing required parameters or invalid properties type
        503:
          description: Service or database unavailable
definitions:
  Task:
    type: object
    properties:
      id:
        type: number
        example: 1
        description: The unique id of the task
      title:
        type: string
        example: Do the laundry
        description: The title of the task
      description:
        type: string
        example: Do not forget to get the laundry done before tomorrow
        description: The description of the task
      status:
        type: string
        example: pending
        enum: ["pending", "in progress", "done"]
        description: The status of the task
  CreateTaskDto:
    type: object
    properties:
      title:
        type: string
        example: Do the laundry
        description: The title of the task
      description:
        type: string
        example: Do not forget to get the laundry done before tomorrow
        description: The description of the task
      status:
        type: string
        example: pending
        enum: ["pending", "in progress", "done"]
        description: The status of the task
    required:
      - title
      - description
  UpdateTaskDto:
    type: object
    properties:
      title:
        type: string
        example: Do the laundry
        description: The title of the task
      description:
        type: string
        example: Do not forget to get the laundry done before tomorrow
        description: The description of the task
      status:
        type: string
        example: pending
        enum: ["pending", "in progress", "done"]
        description: The status of the task
    required:
      - title
      - description
      - status
  UpdateTaskPartiallyDto:
    type: object
    properties:
      title:
        type: string
        example: Do the laundry
        description: The title of the task
      description:
        type: string
        example: Do not forget to get the laundry done before tomorrow
        description: The description of the task
      status:
        type: string
        example: pending
        enum: ["pending", "in progress", "done"]
        description: The status of the task
